In [2]:
# =============================================================================
# ĆELIJA 1: Uvoz biblioteka i učitavanje podataka
# =============================================================================
import pandas as pd
import numpy as np

# Učitavamo Boston dataset (Pazi na putanju, stavi '../data/boston.csv' ako ti je data folder nazad)
data = pd.read_csv('../data/boston.csv')
print("Kako izgledaju naši sirovi podaci:")
data.head()

Kako izgledaju naši sirovi podaci:


,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2


In [3]:
# =============================================================================
# ĆELIJA 2: Izdvajanje X (atributa) i y (ciljne cene)
# =============================================================================
target_col = data.columns[-1]
print(f"Kolona koju predviđamo: {target_col}\n")

Kolona koju predviđamo: MEDV



In [10]:
y = data[[target_col]].to_numpy()
y

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [14]:

X_raw = data.drop(columns=[target_col])

print(f"Dimenzije ciljnih cena y: {y.shape}")
print(f"Dimenzije ulaznih atributa X: {X_raw.shape}")
X_raw

Dimenzije ciljnih cena y: (506, 1)
Dimenzije ulaznih atributa X: (506, 13)


,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48


In [11]:
X_raw.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

In [12]:
X_raw.std()

CRIM         8.601545
ZN          23.322453
INDUS        6.860353
CHAS         0.253994
NOX          0.115878
RM           0.702617
AGE         28.148861
DIS          2.105710
RAD          8.707259
TAX        168.537116
PTRATIO      2.164946
B           91.294864
LSTAT        7.141062
dtype: float64

In [13]:
# =============================================================================
# ĆELIJA 3: KORAK 1 - Normalizacija (Z-Score)
# =============================================================================
# Zašto ovo radimo? Da bismo sve kolone sveli na sličan raspon. Gradijentni spust
# inače ne radi dobro ako su neki brojevi ogromni (npr. porez), a neki mali (broj soba).

X_mean = X_raw.mean()
# 'replace' rešava granični slučaj: sprečava deljenje sa nulom ako su svi podaci isti!
X_std = X_raw.std().replace(0, 1e-9)

# x mean i std su panda series - 1d niz sa indeksom(nazivom)

X_norm = (X_raw - X_mean) / X_std

# sve ih dovodi u raspon npr - 2 do 2, za koliko koraka tj st devijacija je ova vrednost udaljena od proseka

print("Podaci NAKON normalizacije (sada su oko nule):")
X_norm.head()

Podaci NAKON normalizacije (sada su oko nule):


,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.419367,0.284548,-1.286636,-0.272329,-0.144075,0.413263,-0.119895,0.140075,-0.981871,-0.665949,-1.457558,0.440616,-1.074499
1,-0.416927,-0.487240,-0.592794,-0.272329,-0.739530,0.194082,0.366803,0.556609,-0.867024,-0.986353,-0.302794,0.440616,-0.491953
2,-0.416929,-0.487240,-0.592794,-0.272329,-0.739530,1.281446,-0.265549,0.556609,-0.867024,-0.986353,-0.302794,0.396035,-1.207532
3,-0.416338,-0.487240,-1.305586,-0.272329,-0.834458,1.015298,-0.809088,1.076671,-0.752178,-1.105022,0.112920,0.415751,-1.360171
4,-0.412074,-0.487240,-1.305586,-0.272329,-0.834458,1.227362,-0.510674,1.076671,-0.752178,-1.105022,0.112920,0.440616,-1.025487


In [20]:
# =============================================================================
# ĆELIJA 4: KORAK 2 - Dodavanje Bias-a (Slobodnog člana)
# =============================================================================
# Dodajemo kolonu sa jedinicama na KRAJ matrice, kako bi se slobodni član w0 množio sa 1.
X_norm_np = X_norm.to_numpy()
X_norm_np
# ovde smo samo pretvorili u np niz - 2d , svaki unutrasnji niz su samo redovi kuca sa vrednostima iz kolona
# jer navodno nam smetaju imena kolona za matricno mnozenje i guess

13

In [15]:

m = X_norm_np.shape[0] # vraca broj redova - 506

X = np.hstack([X_norm_np, np.ones((m, 1))]) # mergeuje 2 matrice np(ones) - koja je 506x1 i x_norm_Np

print(f"Dimenzije matrice X pre biasa: {X_norm_np.shape}")
print(f"Dimenzije matrice X POSLE biasa: {X.shape} (Dodata 1 kolona)")
print(f"Prvi red podataka sada izgleda ovako (uoči jedinicu na kraju!):\n{X[0]}")

Dimenzije matrice X pre biasa: (506, 13)
Dimenzije matrice X POSLE biasa: (506, 14) (Dodata 1 kolona)
Prvi red podataka sada izgleda ovako (uoči jedinicu na kraju!):
[-0.41936693  0.28454827 -1.28663623 -0.27232907 -0.14407485  0.41326292
 -0.11989477  0.14007498 -0.98187119 -0.66594918 -1.45755797  0.44061589
 -1.07449897  1.        ]


In [26]:
nasumicno = np.random.randn(1, 14)
nasumicno
nasumicno * 0.01

array([[-0.00104743,  0.00631095, -0.00524688,  0.00799673, -0.01060433,
        -0.00475656,  0.00668131,  0.00556789, -0.00151367,  0.01192934,
        -0.01651077,  0.01515425, -0.01241731,  0.00063975]])

In [32]:
# =============================================================================
# ĆELIJA 5: MATEMATIKA - Jedan korak gradijentnog spusta (Pešaka)
# =============================================================================
n = X.shape[1] # broj parametara (14)

# Inicijalizujemo male nasumične parametre
w = np.random.randn(1, n) * 0.01

# randn je za normalnu Gausovu - brojevi blizu nule u dimenziji 1x14
# i jos ih dodatno smanjujemo sa 0.01 jer mogu ici i do 2 i 3

print(f"Početne težine (w) pre učenja:\n{w}\n")

# A) PREDVIĐANJE: Množimo podatke X sa transponovanim težinama w
pred = X @ w.T
pred[1]

# transponovali smo jer je matrica bila 14x1 a zelimo da bude 1x14 zbog 506x14

# za prvi slucaj tj red svaku kolonu mnozi sa odgovarajucom tezinom tj redom iz vektora w
# i na kraju za ceo taj red sabira sve te pomnoske i dobije jedan broj za tu pred kolonu

# pred je sada 1 kolona sa 506 redova naseg predvidjanja

Početne težine (w) pre učenja:
[[-1.25984899e-02 -1.02727588e-03  1.48278192e-02  6.27633261e-03
   8.00797462e-03 -2.08350850e-03  1.09898159e-03  7.15635760e-03
   9.46219073e-03 -1.46046154e-02 -5.83612620e-03 -2.97155474e-04
  -7.77594869e-03  3.70689872e-05]]



array([0.00501403])

In [33]:

# B) GREŠKA: Razlika između našeg predviđanja i pravih cena
err = pred - y
err
# greska je opet 1 kolona sa 506 redova

array([[-23.99973712],
       [-21.59498597],
       [-34.69236885],
       [-33.39845199],
       [-36.20122947],
       [-28.69873049],
       [-22.88663501],
       [-27.09203639],
       [-16.50163528],
       [-18.88752783],
       [-14.99288705],
       [-18.88468727],
       [-21.69128336],
       [-20.40006483],
       [-18.20258405],
       [-19.90086173],
       [-23.10076133],
       [-17.50811053],
       [-20.20631987],
       [-18.20561178],
       [-13.61535441],
       [-19.60778176],
       [-15.21422551],
       [-14.51342183],
       [-15.608699  ],
       [-13.90794129],
       [-16.60576443],
       [-14.81016968],
       [-18.40639456],
       [-21.00735371],
       [-12.71594581],
       [-14.50694906],
       [-13.22347263],
       [-13.11278838],
       [-13.51646139],
       [-18.90410549],
       [-20.00590794],
       [-21.00198384],
       [-24.70467296],
       [-30.80717355],
       [-34.90614059],
       [-26.59205323],
       [-25.29119679],
       [-24

In [34]:

# C) GRADIJENT: Pravac u kom treba da pomerimo težine da bismo smanjili grešku
# delimo sa 506 tj brojem uzoraka jer je to prosecna greska

# znaci err smo vec rekli to je greska za svaki red tj svaku kucu
# onda tu gresku za taj jedan red mnozimo sa kolonom iz date i sabiramo znaci e1xCRIM1 + e2xCRIM2 ...
grad = (err.T @ X) / m
grad

array([[  3.55131649,  -3.30875712,   4.44157649,  -1.59927203,
          3.92384799,  -6.37966749,   3.45918008,  -2.29309318,
          3.49623503,   4.29402563,   4.65247606,  -3.05682944,
          6.76420997, -22.53276926]])

In [31]:

# D) REGULARIZACIJA: Kaznjavamo velike težine, ali NE DIRAMO w0 (poslednji indeks -1)

# postavljamo regularizacioni koeficijent lambda
# znaci da ce u onom azuriranju toliko biti smanjene tezine
lam = 0.1
reg = lam * w.copy()
reg[0, -1] = 0.0
# 0 je prvi red (nas jedini iz 1x14) a -1 je za bias da mu kazna bude 0

grad = grad + reg

# E) AŽURIRANJE: Pomeramo w u pravcu "nizbrdice" (suprotno od gradijenta)

# alfa je learning rate
alpha = 0.01
w = w - alpha * grad

print(f"Težine (w) NAKON jedne iteracije učenja (malo su se promenile!):\n{w}")

Težine (w) NAKON jedne iteracije učenja (malo su se promenile!):
[[-0.0218462   0.03864555 -0.04357204  0.01559306 -0.04128055  0.07169328
  -0.0219655   0.01448995 -0.04438483 -0.04994845 -0.05310484  0.03750517
  -0.04435329  0.21765841]]


In [ ]:
# =============================================================================
# ĆELIJA 6: SPAKUJMO SVE U KLASNE FUNKCIJE
# =============================================================================
def normalize(X):
    mean = X.mean()
    std = X.std().replace(0, 1e-9)
    X_norm = (X - mean) / std
    return X_norm, mean, std

def add_bias(X):
    m = X.shape[0]
    return np.hstack([X, np.ones((m, 1))])

def learn(data, target_col, lam=0.0, alpha=0.01, max_iter=10000, tol=0.01, method='batch', auto_lr=False, verbose=True):
    y = data[[target_col]].to_numpy()
    X_raw = data.drop(columns=[target_col])

    X_norm, X_mean, X_std = normalize(X_raw)
    X = add_bias(X_norm.to_numpy())
    m, n = X.shape

    w = np.random.randn(1, n) * 0.01

    prev_w = None
    prev_grad = None

    for it in range(max_iter):
        pred = X @ w.T
        err = pred - y

        if method == 'sgd':
            # SGD: nasumično biramo samo 1 kuću za proračun!
            idx = np.random.randint(m)
            grad = err[idx] * X[idx].reshape(1, -1)
        else:
            # BATCH: koristimo celu bazu
            grad = (err.T @ X) / m

        # L2 regularizacija — ne penalizujemo slobodni član
        reg = lam * w.copy()
        reg[0, -1] = 0.0
        grad = grad + reg

        # Barzilai-Borwein automatski learning rate (BONUS)
        if auto_lr and method == 'batch' and prev_w is not None:
            delta_w = w - prev_w
            delta_grad = grad - prev_grad
            denom = float(delta_grad @ delta_grad.T)
            if denom > 1e-12:
                alpha = abs(float(delta_w @ delta_grad.T) / denom)

        prev_w = w.copy()
        prev_grad = grad.copy()
        w = w - alpha * grad

        grad_norm = float(np.abs(grad).sum())
        loss = float(np.mean(err ** 2))

        # Ispis svaki 500-ti korak
        if verbose and it % 500 == 0:
            print(f"iter={it:5d} | grad_norm={grad_norm:.6f} | MSE={loss:.4f} | alpha={alpha:.6f}")

        # Uslov za prevremeni izlaz (ako smo stigli do dna brda)
        if grad_norm < tol:
            if verbose:
                print(f"\nKonvergencija u iteraciji {it}")
            break

    return {'w': w, 'X_mean': X_mean, 'X_std': X_std}

def predict(model, data_new):
    # Nove podatke moramo normalizovati starim X_mean i X_std!
    X_norm = (data_new - model['X_mean']) / model['X_std']
    X = add_bias(X_norm.to_numpy())
    return (X @ model['w'].T).flatten()

In [ ]:
# =============================================================================
# ĆELIJA 7: TEST 1 - TRENIRANJE (Osnovni Batch Gradient Descent)
# =============================================================================
print(">> POKREĆEM BATCH GRADIJENTNI SPUST <<")
model_batch = learn(data, target, lam=0.1, alpha=0.01, method='batch', auto_lr=False)

In [ ]:
# =============================================================================
# ĆELIJA 8: TEST 2 - TRENIRANJE (Stohastički - SGD)
# =============================================================================
print(">> POKREĆEM SGD (Samo po jedna kuća u iteraciji) <<")
# Stavljamo mnogo više iteracija, jer 1 iteracija = 1 kuća
# Stavljamo manju alfu, jer SGD mnogo "skače"
model_sgd = learn(data, target, lam=0.1, alpha=0.001, max_iter=50000, method='sgd', auto_lr=False)

In [ ]:
# =============================================================================
# ĆELIJA 9: TEST 3 - TRENIRANJE (Bonus Automatska Alfa)
# =============================================================================
print(">> POKREĆEM BATCH SA AUTOMATSKIM LEARNING RATE-OM <<")
# Pazi koliko će iteracija ovome trebati da konvergira! Skoro trenutno!
model_auto = learn(data, target, lam=0.1, method='batch', auto_lr=True)

In [ ]:
# =============================================================================
# ĆELIJA 10: PREDIKCIJA I EVALUACIJA MODELA
# =============================================================================
# Koristićemo najbolji model (auto) za predikciju na svim podacima
X_test = data.drop(columns=[target])
y_true = data[target].to_numpy()

# Pozivamo funkciju predict
preds = predict(model_auto, X_test)

# Vizuelni prikaz: Prvih 5 predikcija vs Stvarne cene
print("Naša predikcija\t| Stvarna cena")
print("-" * 35)
for i in range(5):
    print(f"{preds[i]:.2f}\t\t| {y_true[i]:.2f}")

# Računamo ukupnu RMSE (Root Mean Square Error) grešku
rmse = np.sqrt(np.mean((preds - y_true) ** 2))
print(f"\nKonačna prosečna greška (RMSE) modela je: {rmse:.4f}")